[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#8b5cf6"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#e5e7eb"
